feature: added sign up page
IgorLeshchenko/star-university-q3-2021-group-2 pull request #40
Opened 2021-11-03 19:32 UTC by vihopec

2021-11-03 22:42 UTC, Chubatik requested changes
Move constants API_URL and TEXT_VARIANTS to folder src/constants

2021-11-04 07:32 UTC, YanaGushlevskaya commented
Let's move common components (TextField, Button, Typography) to 'src/shared' folder

2021-11-04 07:52 UTC, YanaGushlevskaya commented on src/pages/sign-up/schema.ts
> +  password: yup.string().min(5, 'Password should be 5 chars min!').required('Password is required'),
Please, change to 8 min length (according to API requirements).

2021-11-04 09:05 UTC, IgorLeshchenko commented on src/components/Button/index.tsx
> +const Button = ({ className, type = 'button', disabled, children, primary = false }: IButton) => {
```
interface Props = {
   ...
}

const Button: React.FC<Props> = ({ ... }) => {
```

2021-11-04 09:25 UTC, irenlian commented on src/App.tsx
> +            <Route exact={true} path={Routes.POSTS} component={Posts} />
```suggestion
            <Route exact path={Routes.POSTS} component={Posts} />
```

2021-11-04 09:25 UTC, irenlian commented on src/components/TextField/index.tsx
> +  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void
```suggestion
  onChange: React.ChangeEventHandler<HTMLInputElement>
```

2021-11-04 09:25 UTC, irenlian commented on src/components/TextField/index.tsx
> +  helperText?: string | undefined | boolean
If you use `?` it already means `undefined` as a possible value.
I wouldn't recommend storing in a single prop string & boolean simultaneously.

2021-11-04 09:25 UTC, irenlian commented on src/components/TextField/index.tsx
> +const TextField = ({ className, id, name, label, type, value, onChange, error, helperText }: ITextField) => {
I'd suggest to clarify the types for components as well.
```suggestion
const TextField: React.FC< ITextField> = ({ className, id, name, label, type, value, onChange, error, helperText }) => {
```

2021-11-04 09:25 UTC, irenlian commented on src/components/Typography/index.tsx
> +const Typography = ({ className, variant = TEXT_VARIANTS.BODY, children }: ITypography) => {
```suggestion
interface ITypography {
  variant?: TEXT_VARIANTS
}

const TypographyReact.FC<PropsWithChildren<ITypography>> = ({ className, variant = TEXT_VARIANTS.BODY, children }) => {
```

2021-11-04 09:25 UTC, irenlian commented on src/utils/api.ts
> +  return fetch(`${API_URL}${url}`, {
Why did you pick `fetch` and not `axios`?

2021-11-04 09:53 UTC, Chubatik commented on src/utils/api.ts
> +  return fetch(`${API_URL}${url}`, {
API will be using axios in the next PR

2021-11-04 11:59 UTC, vihopec commented on src/pages/sign-up/schema.ts
> +  password: yup.string().min(5, 'Password should be 5 chars min!').required('Password is required'),
Fixed

2021-11-04 11:59 UTC, vihopec commented on src/components/Button/index.tsx
> +const Button = ({ className, type = 'button', disabled, children, primary = false }: IButton) => {
Fixed

2021-11-04 12:00 UTC, vihopec commented on src/App.tsx
> +            <Route exact={true} path={Routes.POSTS} component={Posts} />
Fixed

2021-11-04 12:00 UTC, vihopec commented on src/components/TextField/index.tsx
> +  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void
Fixed

2021-11-04 12:00 UTC, vihopec commented on src/components/TextField/index.tsx
> +  helperText?: string | undefined | boolean
Fixed, thanks

2021-11-04 12:00 UTC, vihopec commented on src/components/TextField/index.tsx
> +const TextField = ({ className, id, name, label, type, value, onChange, error, helperText }: ITextField) => {
Fixed

2021-11-04 12:00 UTC, vihopec commented on src/components/Typography/index.tsx
> +const Typography = ({ className, variant = TEXT_VARIANTS.BODY, children }: ITypography) => {
Fixed

2021-11-04 12:29 UTC, Chubatik approved these changes

2021-11-04 12:45 UTC, IgorLeshchenko approved these changes

2021-11-04 12:52 UTC, YanaGushlevskaya approved these changes

2021-11-04 13:28 UTC, merged