#53 Added scroll to top component
IgorLeshchenko/star-university-q3-2021-group-2 pull request #62
Opened 2021-11-11 14:07 UTC by Chubatik

2021-11-11 16:30 UTC, irenlian requested changes

2021-11-11 16:30 UTC, irenlian commented on src/components/ScrollToTop/index.tsx
> +export const ScrollToTop: React.FC = React.memo(() => {
It would be easier to use default export so you could extract React.memo:
`export default React.memo(ScrollToTop);`
But anyway, I'd recommend separating export with memoization from the actual component:
```
const C = () => {}
export const ScrollToTop = React.memo(C);
```
Because as soon as you have additional props, this will become tricky to read.

2021-11-11 16:30 UTC, irenlian commented on src/components/ScrollToTop/index.tsx
> +    if (window.scrollY > 500) {
Please, check if you need to use exactly `window` and not `document`. 
https://stackoverflow.com/questions/48443225/listening-to-scroll-event-on-window-vs-on-document-leads-to-conflict-between-ha
https://javascript.info/size-and-scroll-window

2021-11-11 16:30 UTC, irenlian commented on src/components/ScrollToTop/index.tsx
> +  window.addEventListener('scroll', toggleVisibility)
Here are two problems with this approach: 
- `toggleVisibility` will be triggered X times equals to each pixel of the scroll - not performant. Consider lodash debouce
- when the user switches from this page that contained `ScrollToTop` to other that doesn't, `toggleVisibility` will be still triggered

2021-11-11 17:57 UTC, Chubatik commented on src/components/ScrollToTop/index.tsx
> +    if (window.scrollY > 500) {
But if i will use `document` for adding listener to avoid listening on the other pages, and `window` only for scroll to top and getting scroll position. Is it valid approach ?

2021-11-11 17:59 UTC, Chubatik commented on src/components/ScrollToTop/index.tsx
> +    if (window.scrollY > 500) {
Or could I unsubscribe from event in useEffect ?

2021-11-12 12:09 UTC, KolomiietsAn approved these changes

2021-11-12 14:11 UTC, YanaGushlevskaya approved these changes

2021-11-12 14:43 UTC, merged